CREATE SCHEMA NASCI;
USE NASCI;

CREATE TABLE STATE(
ID_STATE SMALLINT NOT NULL,
STATE_NAME CHAR(30),
CITY CHAR (30),
PRIMARY KEY (ID_STATE)
);
DESC STATE;

CREATE TABLE ADDRESS(
CEP CHAR(8) NOT NULL,
LOGRADOURO VARCHAR(50) NOT NULL,
NUMERO VARCHAR(5) NOT NULL,
COMPLEMENTO VARCHAR(20),
PRIMARY KEY (CEP, NUMERO)
);
DESC ADDRESS;

CREATE TABLE SIGN_UP(
NOME_COMPLETO VARCHAR(60) NOT NULL,
DATA_NASCIMENTO DATE NOT NULL,
CPF CHAR(11) NOT NULL,
CNH CHAR(11),
RG CHAR(7),
PRIMARY KEY (CPF)
);
DESC SIGN_UP;


CREATE TABLE PERSON2(
NOME_COMPLETO VARCHAR(60),
DATA_NASCIMENTO DATE,
CPF CHAR(11),
CNH CHAR(12),
RG CHAR(7),
PRIMARY KEY (CPF)
);
DESC PERSON2;

CREATE TABLE TELEPHONES(
CPF CHAR (11),
TELEPHONE CHAR(11),
PRIMARY KEY (CPF)
);
DESC TELEPHONES;

CREATE TABLE DOCUMENTS(
WEDDING_CERTIFICATE VARCHAR (50),
BIRTH_CERTIFICATE VARCHAR(50),
CPF CHAR(11),
PRIMARY KEY (CPF)
);
DESC DOCUMENTS;

CREATE TABLE EMAIL(
EMAIL VARCHAR (50),
CPF CHAR(11),
PRIMARY KEY (CPF)
);
DESC EMAIL;

CREATE TABLE PASSWORD2(
PASSWORD2 VARCHAR (50),
CPF CHAR (11),
PRIMARY KEY (CPF)
);
DESC PASSWORD2;

CREATE TABLE KIDS(
NASCIDO_VIVO CHAR(12) NOT NULL,
PRIMARY KEY (NASCIDO_VIVO)

);
DESC KIDS;

CREATE TABLE SERVICE_ORDER(
COD_SERVICE CHAR(10) NOT NULL,
EMISSION_DATE DATE NOT NULL,
ORDER_STATUS CHAR(10) NOT NULL,
SIGNATURE CHAR(60) NOT NULL,
PRIMARY KEY (COD_SERVICE)

);
DESC SERVICE_ORDER;

CREATE TABLE ADDRESS_REGISTRY(
CEP CHAR(8) NOT NULL,
LOGRADOURO VARCHAR(50) NOT NULL,
NUMERO VARCHAR(5) NOT NULL,
COMPLEMENTO VARCHAR(20) NOT NULL,
CNPJ CHAR(15),
PRIMARY KEY (CNPJ)
);
DESC ADDRESS_REGISTRY;

CREATE TABLE PHONE_REGISTRY(
PHONE_NUMBER CHAR(11) NOT NULL,
CNPJ CHAR(15),
PRIMARY KEY (PHONE_NUMBER)
);
DESC PHONE_REGISTRY;

CREATE TABLE REGISTRY(
EMAIL CHAR(60) NOT NULL,
CNPJ CHAR(15),
PRIMARY KEY (CNPJ)

);
DESC REGISTRY